site:
  title: Arotna
  url: http://arotna.org
  start_page: arotna::index 
content:
  sources:
  - url: https://github.com/finp/arotna.org.git
    branches: master
ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
